// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the main Wails service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddPostIt creates a new sticky note with the given title.
 */
export function AddPostIt(title: string): $CancellablePromise<$models.PostIt> {
    return $Call.ByID(114746987, title).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AddPostItWithPath creates a new sticky note linked to an existing file.
 */
export function AddPostItWithPath(title: string, path: string): $CancellablePromise<$models.PostIt> {
    return $Call.ByID(3498993876, title, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * BrowseBaseDir opens a folder picker dialog and returns the selected path.
 */
export function BrowseBaseDir(): $CancellablePromise<string> {
    return $Call.ByID(1726818729);
}

/**
 * BrowseFile opens a file picker dialog and returns the selected path.
 */
export function BrowseFile(): $CancellablePromise<string> {
    return $Call.ByID(3416317617);
}

/**
 * DeletePostIt removes a sticky note from the list (does not delete file).
 */
export function DeletePostIt(id: string): $CancellablePromise<void> {
    return $Call.ByID(1097967065, id);
}

/**
 * DeletePostItAndFile removes a sticky note and deletes its file.
 */
export function DeletePostItAndFile(id: string): $CancellablePromise<void> {
    return $Call.ByID(3275854948, id);
}

/**
 * GetAutostartEnabled returns whether autostart is enabled.
 */
export function GetAutostartEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(3889022481);
}

/**
 * GetBaseDir returns the current base directory.
 */
export function GetBaseDir(): $CancellablePromise<string> {
    return $Call.ByID(1204833849);
}

/**
 * GetContent reads and returns the file contents for a sticky note.
 */
export function GetContent(id: string): $CancellablePromise<string> {
    return $Call.ByID(2616121816, id);
}

/**
 * GetPalettePostIts returns sticky notes ordered by recent open activity.
 */
export function GetPalettePostIts(): $CancellablePromise<$models.PostIt[]> {
    return $Call.ByID(4078169090).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetPostItByID returns a single sticky note by ID.
 */
export function GetPostItByID(id: string): $CancellablePromise<$models.PostIt | null> {
    return $Call.ByID(2270654980, id).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetPostIts returns all sticky notes.
 */
export function GetPostIts(): $CancellablePromise<$models.PostIt[]> {
    return $Call.ByID(1467412597).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetTheme returns the current theme preset ID.
 */
export function GetTheme(): $CancellablePromise<string> {
    return $Call.ByID(1815524992);
}

/**
 * HideCommandPalette hides the command palette window.
 */
export function HideCommandPalette(): $CancellablePromise<void> {
    return $Call.ByID(443703853);
}

/**
 * Init loads config, starts the file watcher, and registers hotkeys.
 * Called after SetSettingsWin, before app.Run().
 */
export function Init(): $CancellablePromise<void> {
    return $Call.ByID(2832927211);
}

/**
 * InitWindowsAndTray is called by the frontend after it is ready.
 * Windows are created lazily on first TogglePostitWindow call.
 */
export function InitWindowsAndTray(): $CancellablePromise<void> {
    return $Call.ByID(3562779129);
}

/**
 * ListBaseDirFiles returns all .md files in the base directory.
 */
export function ListBaseDirFiles(): $CancellablePromise<string[]> {
    return $Call.ByID(1998384994).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * OpenBaseDir opens the base directory in Windows Explorer.
 */
export function OpenBaseDir(): $CancellablePromise<void> {
    return $Call.ByID(2828129683);
}

/**
 * OpenPostItInEditor opens the sticky note file in the system's default editor.
 */
export function OpenPostItInEditor(id: string): $CancellablePromise<void> {
    return $Call.ByID(2216532372, id);
}

/**
 * SetAutostartEnabled enables or disables autostart.
 */
export function SetAutostartEnabled(enable: boolean): $CancellablePromise<void> {
    return $Call.ByID(2651399725, enable);
}

/**
 * SetBaseDir changes the base directory.
 */
export function SetBaseDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(1736883101, dir);
}

/**
 * SetTheme changes the active theme preset and broadcasts the update.
 */
export function SetTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(3669652676, theme);
}

/**
 * TogglePalettePostIt toggles the selected sticky note and hides the command palette.
 */
export function TogglePalettePostIt(id: string): $CancellablePromise<void> {
    return $Call.ByID(2459222335, id);
}

/**
 * TogglePostitWindow shows or hides the window for the given sticky note.
 */
export function TogglePostitWindow(id: string): $CancellablePromise<void> {
    return $Call.ByID(1541560526, id);
}

/**
 * UpdatePostIt saves changes to an existing sticky note (title, hotkey).
 */
export function UpdatePostIt(updated: $models.PostIt): $CancellablePromise<void> {
    return $Call.ByID(1722755771, updated);
}

// Private type creation functions
const $$createType0 = $models.PostIt.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Nullable($$createType0);
const $$createType3 = $Create.Array($Create.Any);
