// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the main Wails service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddPostIt creates a new sticky note with the given title.
 * @param {string} title
 * @returns {$CancellablePromise<$models.PostIt>}
 */
export function AddPostIt(title) {
    return $Call.ByID(114746987, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AddPostItWithPath creates a new sticky note linked to an existing file.
 * @param {string} title
 * @param {string} path
 * @returns {$CancellablePromise<$models.PostIt>}
 */
export function AddPostItWithPath(title, path) {
    return $Call.ByID(3498993876, title, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * BrowseBaseDir opens a folder picker dialog and returns the selected path.
 * @returns {$CancellablePromise<string>}
 */
export function BrowseBaseDir() {
    return $Call.ByID(1726818729);
}

/**
 * BrowseFile opens a file picker dialog and returns the selected path.
 * @returns {$CancellablePromise<string>}
 */
export function BrowseFile() {
    return $Call.ByID(3416317617);
}

/**
 * DeletePostIt removes a sticky note from the list (does not delete file).
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeletePostIt(id) {
    return $Call.ByID(1097967065, id);
}

/**
 * DeletePostItAndFile removes a sticky note and deletes its file.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeletePostItAndFile(id) {
    return $Call.ByID(3275854948, id);
}

/**
 * GetAutostartEnabled returns whether autostart is enabled.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetAutostartEnabled() {
    return $Call.ByID(3889022481);
}

/**
 * GetBaseDir returns the current base directory.
 * @returns {$CancellablePromise<string>}
 */
export function GetBaseDir() {
    return $Call.ByID(1204833849);
}

/**
 * GetContent reads and returns the file contents for a sticky note.
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function GetContent(id) {
    return $Call.ByID(2616121816, id);
}

/**
 * GetPalettePostIts returns sticky notes ordered by recent open activity.
 * @returns {$CancellablePromise<$models.PostIt[]>}
 */
export function GetPalettePostIts() {
    return $Call.ByID(4078169090).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetPostItByID returns a single sticky note by ID.
 * @param {string} id
 * @returns {$CancellablePromise<$models.PostIt | null>}
 */
export function GetPostItByID(id) {
    return $Call.ByID(2270654980, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetPostIts returns all sticky notes.
 * @returns {$CancellablePromise<$models.PostIt[]>}
 */
export function GetPostIts() {
    return $Call.ByID(1467412597).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetTheme returns the current theme preset ID.
 * @returns {$CancellablePromise<string>}
 */
export function GetTheme() {
    return $Call.ByID(1815524992);
}

/**
 * HideCommandPalette hides the command palette window.
 * @returns {$CancellablePromise<void>}
 */
export function HideCommandPalette() {
    return $Call.ByID(443703853);
}

/**
 * Init loads config, starts the file watcher, and registers hotkeys.
 * Called after SetSettingsWin, before app.Run().
 * @returns {$CancellablePromise<void>}
 */
export function Init() {
    return $Call.ByID(2832927211);
}

/**
 * InitWindowsAndTray is called by the frontend after it is ready.
 * Creates postit windows and returns.
 * @returns {$CancellablePromise<void>}
 */
export function InitWindowsAndTray() {
    return $Call.ByID(3562779129);
}

/**
 * ListBaseDirFiles returns all .md files in the base directory.
 * @returns {$CancellablePromise<string[]>}
 */
export function ListBaseDirFiles() {
    return $Call.ByID(1998384994).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * OpenBaseDir opens the base directory in Windows Explorer.
 * @returns {$CancellablePromise<void>}
 */
export function OpenBaseDir() {
    return $Call.ByID(2828129683);
}

/**
 * OpenPostItInEditor opens the sticky note file in the system's default editor.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function OpenPostItInEditor(id) {
    return $Call.ByID(2216532372, id);
}

/**
 * SetAutostartEnabled enables or disables autostart.
 * @param {boolean} enable
 * @returns {$CancellablePromise<void>}
 */
export function SetAutostartEnabled(enable) {
    return $Call.ByID(2651399725, enable);
}

/**
 * SetBaseDir changes the base directory.
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function SetBaseDir(dir) {
    return $Call.ByID(1736883101, dir);
}

/**
 * SetTheme changes the active theme preset and broadcasts the update.
 * @param {string} theme
 * @returns {$CancellablePromise<void>}
 */
export function SetTheme(theme) {
    return $Call.ByID(3669652676, theme);
}

/**
 * TogglePalettePostIt toggles the selected sticky note and hides the command palette.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function TogglePalettePostIt(id) {
    return $Call.ByID(2459222335, id);
}

/**
 * TogglePostitWindow shows or hides the window for the given sticky note.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function TogglePostitWindow(id) {
    return $Call.ByID(1541560526, id);
}

/**
 * UpdatePostIt saves changes to an existing sticky note (title, hotkey).
 * @param {$models.PostIt} updated
 * @returns {$CancellablePromise<void>}
 */
export function UpdatePostIt(updated) {
    return $Call.ByID(1722755771, updated);
}

// Private type creation functions
const $$createType0 = $models.PostIt.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Nullable($$createType0);
const $$createType3 = $Create.Array($Create.Any);
