// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PostIt represents a sticky note entry.
 */
export class PostIt {
    "id": string;
    "title": string;
    "path": string;
    "hotkey": string;

    /** Creates a new PostIt instance. */
    constructor($$source: Partial<PostIt> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("hotkey" in $$source)) {
            this["hotkey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PostIt instance from a string or object.
     */
    static createFrom($$source: any = {}): PostIt {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PostIt($$parsedSource as Partial<PostIt>);
    }
}
