// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PostIt represents a sticky note entry.
 */
export class PostIt {
    /**
     * Creates a new PostIt instance.
     * @param {Partial<PostIt>} [$$source = {}] - The source object to create the PostIt.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("hotkey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hotkey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PostIt instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PostIt}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PostIt(/** @type {Partial<PostIt>} */($$parsedSource));
    }
}
