export const COMMON_THEME_SEEDS = [
  { id: "obsidian", name: "Obsidian", accent: "#f8fafc" },
  { id: "graphite", name: "Graphite", accent: "#cbd5e1" },
  { id: "ruby", name: "Ruby", accent: "#ef4444" },
  { id: "ember", name: "Ember", accent: "#f97316" },
  { id: "amber", name: "Amber", accent: "#f59e0b" },
  { id: "citron", name: "Citron", accent: "#eab308" },
  { id: "lime", name: "Lime", accent: "#84cc16" },
  { id: "moss", name: "Moss", accent: "#65a30d" },
  { id: "green", name: "Green", accent: "#22c55e" },
  { id: "emerald", name: "Emerald", accent: "#10b981" },
  { id: "teal", name: "Teal", accent: "#14b8a6" },
  { id: "cyan", name: "Cyan", accent: "#06b6d4" },
  { id: "sky", name: "Sky", accent: "#38bdf8" },
  { id: "blue", name: "Blue", accent: "#3b82f6" },
  { id: "navy", name: "Navy", accent: "#1d4ed8" },
  { id: "indigo", name: "Indigo", accent: "#6366f1" },
  { id: "violet", name: "Violet", accent: "#8b5cf6" },
  { id: "purple", name: "Purple", accent: "#a855f7" },
  { id: "fuchsia", name: "Fuchsia", accent: "#d946ef" },
  { id: "pink", name: "Pink", accent: "#ec4899" },
  { id: "rose", name: "Rose", accent: "#f43f5e" },
  { id: "coral", name: "Coral", accent: "#fb7185" },
  { id: "copper", name: "Copper", accent: "#c2410c" },
  { id: "mocha", name: "Mocha", accent: "#8b5e3c" },
];

export const PASTEL_THEME_SEEDS = [
  { id: "pastel-cloud", name: "Cloud", accent: "#e2e8f0" },
  { id: "pastel-fog", name: "Fog", accent: "#d8dee9" },
  { id: "pastel-mist", name: "Mist", accent: "#dbeafe" },
  { id: "pastel-skywash", name: "Skywash", accent: "#bfdbfe" },
  { id: "pastel-periwinkle", name: "Periwinkle", accent: "#c7d2fe" },
  { id: "pastel-lavender", name: "Lavender", accent: "#ddd6fe" },
  { id: "pastel-lilac", name: "Lilac", accent: "#e9d5ff" },
  { id: "pastel-orchid", name: "Orchid", accent: "#f5d0fe" },
  { id: "pastel-blush", name: "Blush", accent: "#fbcfe8" },
  { id: "pastel-petal", name: "Petal", accent: "#fecdd3" },
  { id: "pastel-peach", name: "Peach", accent: "#fed7aa" },
  { id: "pastel-apricot", name: "Apricot", accent: "#fde2c0" },
  { id: "pastel-butter", name: "Butter", accent: "#fef3c7" },
  { id: "pastel-lemon", name: "Lemon", accent: "#fef9c3" },
  { id: "pastel-pistachio", name: "Pistachio", accent: "#d9f99d" },
  { id: "pastel-sage", name: "Sage", accent: "#dcfce7" },
  { id: "pastel-mint", name: "Mint", accent: "#ccfbf1" },
  { id: "pastel-seafoam", name: "Seafoam", accent: "#a7f3d0" },
  { id: "pastel-aqua", name: "Aqua", accent: "#cffafe" },
  { id: "pastel-glacier", name: "Glacier", accent: "#e0f2fe" },
  { id: "pastel-oat", name: "Oat", accent: "#f5f1e8" },
  { id: "pastel-sand", name: "Sand", accent: "#ead7b7" },
  { id: "pastel-clay", name: "Clay", accent: "#f2d1c9" },
  { id: "pastel-melon", name: "Melon", accent: "#fdc9b6" },
];
